a = int(input())
b = int(input())
c = int(input())
sum = str(a * b * c)
print(sum.count('0'))
print(sum.count('1'))
print(sum.count('2'))
print(sum.count('3'))
print(sum.count('4'))
print(sum.count('5'))
print(sum.count('6'))
print(sum.count('7'))
print(sum.count('8'))
print(sum.count('9'))
    
